[build-system]
requires = [
    "setuptools"
]

[project]
name = "barcodeEZ"
version = "1.0.0"
authors = [
    {name="Zach Goode", email="goodez@ohsu.edu"}
]
requires-python = ">=3.10"
dependencies = [
    "biopython >= 1.81",
    "pandas",
]

readme = "README.md"

[project.optional-dependencies]
test = ["pytest"]
docs = ["mkdocs", "mkdocs-material", "mkdocstrings[python]"]

[project.urls]
repository = "https://github.com/barcodeEZ/barcodeEZ"

[tool.setuptools]
packages = ["barcodeEZ"]

[tool.setuptools.package-data]
barcodeEZ = ["corpus/*.fa.gz"]
