[build-system]
requires = [
    "setuptools"
]

[project]
name = "barcodeEZ"
version = "0.1"
authors = [
    {name="Zach Goode"},
    {email="goodez@ohsu.edu"}
]
requires-python = ">=3.8"
dependencies = [
    "pandas >= 2.1.1",
    "parasail >= 1.3.4",
    "scikit-bio >= 0.5.9",
    "matplotlib >= 3.8.4",
    "jinja2 >= 3.1.4",
    "seaborn >= 0.13.2",
    "Porechop@git+https://github.com/rrwick/Porechop.git"
]

readme = "README.md"

[project.urls]
repository = "https://github.com/barcodeEZ/barcodeEZ"

[tool.setuptools]
packages = ["barcodeEZ"]

[tool.setuptools.package-data]
my_package = ["bc_gen/*.fa"]
